apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd      
spec:
  project: default
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.26.1
    helm:
      releaseName: vault
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).   
    syncOptions:
      - CreateNamespace=true
