apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs-jiva
  namespace: argocd      
spec:
  project: default
  destination:
    namespace: openebs
    server: https://kubernetes.default.svc
  source:
    chart: jiva
    repoURL: https://openebs.github.io/jiva-operator
    targetRevision: 3.2.0
    helm:
      releaseName: openebs
      parameters:
        - name: "storageClass.isDefaultClass"
          value: "true"
  syncPolicy:
    automated:
      prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).   
    syncOptions:
      - CreateNamespace=true
