apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: metallb      
spec:
  project: default
  destination:
    namespace: metallb
    server: https://kubernetes.default.svc
  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.13.12
    helm:
      releaseName: metallb
  syncPolicy:
    automated:
      prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).   
    syncOptions:
      - CreateNamespace=true
